import json
import os

records = [
    {
        "doc_name": "0632.pdf",
        "title": "Non-Inclusive Online Security: Older Adults' Experience with Two-Factor Authentication",
        "year": "2021",
        "aim": "To investigate the usability and adoption challenges of hardware-based Two-Factor Authentication (2FA) security keys among older adults (≥ 60 years) to understand digital security exclusion.",
        "objectives": "1. Evaluate older adults' sustained (non)usage of 2FA keys over a 30-day period.\n2. Identify physical, cognitive, and procedural halt points during key setup and daily authentication.\n3. Propose inclusive design modifications and conceptualize support models ('Security Caregivers') to preserve digital independence.",
        "research_questions": "RQ1: What factors contribute to older adults' negative perception and non-adoption of 2FA?\nRQ2: What factors could facilitate the adoption of 2FA by older adults?",
        "methodology": "Qualitative usability field study with N=10 older adults (≥ 60 years) across 30 days. Employed a think-aloud protocol during registration, initial semi-structured interview and survey, a 30-day in-situ trial using Yubico Security Keys (U2F/FIDO2), and a 1-month follow-up survey.",
        "model_used": "Think-Aloud Usability Protocol; Thematic Qualitative Analysis (Boyatzis framework); Cognitive Plasticity & Halt-Point Modeling; Value-Sensitive Design Framework.",
        "conclusion": "Hardware security keys suffer from non-inclusive physical design (small form factors, difficult ports), lack of perceived tangible benefits, inconsistent cross-service instructions, and device dependencies. Introduces the concept of 'Security Caregivers' to provide trusted, bounded technical assistance without compromising user autonomy.",
        "further_areas_research": "Formalizing the legal, ethical, and operational bounds of 'Security Caregivers'; designing multi-modal adaptive 2FA interfaces accommodating age-related motor/visual declines; testing 2FA across larger cohorts with varying levels of cognitive plasticity."
    },
    {
        "doc_name": "1908.05897v1.pdf",
        "title": "All About Phishing: Exploring User Research through a Systematic Literature Review",
        "year": "2019",
        "aim": "To synthesize user-centered phishing literature, evaluate how human factors are investigated, and identify pervasive methodological gaps and recruitment biases in usable security research.",
        "objectives": "1. Conduct a systematic literature review of peer-reviewed phishing papers in the ACM Digital Library (2004–2019).\n2. Determine the proportion and characteristics of studies employing empirical user methodologies.\n3. Analyze participant demographic reporting rigor, recruitment biases, and intervention types (warnings, training, games).",
        "research_questions": "RQ1: To what extent does existing phishing literature focus on end-users rather than purely technical mitigations?\nRQ2: What methodologies, participant demographics, and experimental protocols are commonly employed or underreported in user-centric phishing studies?",
        "methodology": "Systematic Literature Review (SLR) covering 2004–2019 in the ACM Digital Library. Filtered N=367 total phishing papers, identifying n=51 (13.9%) user studies. Conducted thematic coding across participant demographics, methodology types (surveys, interviews, lab experiments), and warning/training interventions.",
        "model_used": "PRISMA-guided Systematic Literature Review; Content Analysis & Thematic Coding; Recruitment Bias & Participant Reporting Rigor Audit.",
        "conclusion": "User-focused research is severely underrepresented (only 13.9% of phishing literature). Furthermore, existing user studies suffer from pervasive underreporting of participant demographics (sample size, background) and heavy recruitment biases (over-reliance on university students). Most studies focus on technical detection tools rather than understanding underlying mental models.",
        "further_areas_research": "Conducting longitudinal in-the-wild phishing studies; incorporating diverse and vulnerable user demographics (older adults, low-literacy users); exploring user mental models and situational context behind phishing susceptibility; establishing standardized reporting guidelines for usable security experiments."
    },
    {
        "doc_name": "2101.07377v1.pdf",
        "title": "Humans and Technology for Inclusive Privacy and Security",
        "year": "2021",
        "aim": "To establish an interdisciplinary research agenda addressing sociotechnical vulnerabilities and non-inclusive design in cybersecurity and privacy for marginalized populations.",
        "objectives": "1. Examine sociotechnical vulnerabilities arising from non-inclusive security/privacy design.\n2. Explore value-sensitive design frameworks for vulnerable groups (older adults, adolescents, persons with disabilities).\n3. Formulate human factors and ergonomics (HFE) principles for accessible cybersecurity tools.",
        "research_questions": "RQ1: How do existing cybersecurity tools fail vulnerable and marginalized populations due to non-inclusive design assumptions?\nRQ2: How can human factors and value-sensitive design bridge the gap between technical security requirements and diverse user capabilities?",
        "methodology": "Expert panel presentation and consensus methodology organized by the HFES Cybersecurity Technical Group, featuring 7 leading researchers across HCI, usable security, and cognitive engineering, synthesizing findings across multiple empirical case studies (smart toys, 2FA for elders, password sharing).",
        "model_used": "Value-Sensitive Design (VSD) Framework; Sociotechnical Vulnerability Framework; Human Factors & Ergonomics (HFE) Expert Panel Synthesis.",
        "conclusion": "Cybersecurity guidance traditionally treats users as a monolithic, technologically proficient group, creating severe exclusion for older adults, youth, and disabled individuals. Inclusive security requires acknowledging cognitive, physiological, and social differences rather than enforcing rigid, one-size-fits-all security mandates.",
        "further_areas_research": "Developing inclusive authentication benchmarks; empirical evaluations of privacy tools across intersectional marginalized user groups; creating policy and technical mechanisms that balance institutional security compliance with user accessibility."
    },
    {
        "doc_name": "2103.14155v2.pdf",
        "title": "Location Data and COVID-19 Contact Tracing: How Data Privacy Regulations and Cell Service Providers Work In Tandem",
        "year": "2021",
        "aim": "To evaluate the tension between public health mobile location tracking for COVID-19 contact tracing and user data privacy protections under major global privacy regulations and cellular service provider policies.",
        "objectives": "1. Evaluate how major privacy legislations (GDPR, CCPA, COPPA, HIPAA, FERPA, CalOPPA) govern Mobile Location Data (MLD).\n2. Audit the privacy policies of five leading U.S. Cellphone Service Providers (CSPs: AT&T, Verizon, T-Mobile, Sprint, Boost Mobile).\n3. Identify regulatory compliance gaps and provide privacy-preserving contact tracing recommendations.",
        "research_questions": "RQ1: How do major global and national privacy regulations govern the collection and sharing of mobile location data?\nRQ2: Do leading cellphone service providers comply with these regulatory frameworks, particularly regarding sensitive populations like children?",
        "methodology": "Comparative policy and regulatory compliance analysis. Mapped 6 major data privacy frameworks against the privacy policies and data handling disclosures of 5 major U.S. CSPs across 10 evaluation parameters (data definition, third-party sharing, opt-out mechanisms, retention, encryption).",
        "model_used": "Privacy by Design Framework (Cavoukian); Comparative Legal/Regulatory Compliance Analysis; Thematic Policy Audit.",
        "conclusion": "Three regulations (GDPR, COPPA, CCPA) explicitly classify mobile location data as private personal information. Two of the five CSPs (T-Mobile US and Boost Mobile) exhibited non-compliance with COPPA regarding location tracking of minors. Significant opacity exists in CSP data-sharing practices with third parties and government entities.",
        "further_areas_research": "Empirical network traffic inspection of CSP data streams beyond declared policies; evaluating privacy-preserving contact tracing architectures (e.g., DP-3T, Google/Apple Exposure Notification); assessing policy updates and location tracking practices post-pandemic."
    },
    {
        "doc_name": "2211.07366v1.pdf",
        "title": "User Perception and Actions Through Risk Analysis Concerning Cookies",
        "year": "2022",
        "aim": "To assess user awareness and risk perception regarding first- and third-party web cookies and evaluate the effectiveness of participatory risk communication interventions on browsing privacy behaviors.",
        "objectives": "1. Design informative educational artifacts (videos and learning website) using participatory design.\n2. Conduct a controlled experiment comparing a control group with an intervention group.\n3. Measure changes in risk perception, threat valuation, and privacy-protective actions regarding targeted advertising and cookies.",
        "research_questions": "RQ1: What is the baseline understanding of users regarding the privacy risks posed by first- and third-party cookies?\nRQ2: Does participatory educational risk communication significantly shift user privacy preferences and protective behaviors?",
        "methodology": "Mixed-methods experimental study. Phase 1: Participatory design workshop (N=15) to co-create educational videos and website. Phase 2: Controlled survey experiment with N=68 participants divided into Control Group (n=30) and Experimental Group (n=38) who engaged with the educational material before answering risk assessment questions.",
        "model_used": "Participatory Design Framework; Control vs. Experimental Comparative Analysis; Descriptive & Inferential Survey Statistics; Risk Perception Likert Scaling.",
        "conclusion": "Users have low baseline knowledge regarding cookie tracking despite having technical backgrounds. Educational risk communication significantly elevated threat awareness: ~68.4% of the experimental group recognized cookies as a moderate-to-severe threat compared to only 38.9% in the control group, resulting in higher intent to block trackers and conceal location.",
        "further_areas_research": "Scaling the evaluation to broader crowdsourced demographic samples; conducting eye-tracking and behavioral telemetry studies during live web browsing; evaluating long-term retention of privacy protective behaviors."
    },
    {
        "doc_name": "2302.01401v1.pdf",
        "title": "A Transcontinental Analysis of Account Remediation Protocols of Popular Websites",
        "year": "2023",
        "aim": "To conduct the first global, transcontinental empirical audit of account remediation protocols across popular websites to evaluate the availability, completeness, and disparity of guidance provided to users with compromised accounts.",
        "objectives": "1. Establish an account remediation evaluation framework covering five core phases.\n2. Audit the top 50 popular websites across 30 countries in 5 continents (Africa, Americas, Asia, Europe, Oceania; N=1,500 websites evaluated).\n3. Analyze regional disparities in remediation advice, especially between Global North and Global South.",
        "research_questions": "RQ1: What remediation guidance and technical mechanisms do popular global websites provide to users following an account compromise?\nRQ2: How does the availability and quality of account remediation advice differ across continents and geopolitical regions?",
        "methodology": "Quantitative empirical web audit. Evaluated the top 50 websites across 30 countries (6 countries per continent) using SimilarWeb rankings. Analyzed 5 distinct remediation stages: Compromise Discovery, Account Recovery, Access Limitation, Service Restoration, and Prevention. Utilized automated and manual inspection with multi-language translation.",
        "model_used": "5-Stage Account Remediation Framework (Discovery, Recovery, Limitation, Restoration, Prevention); Cross-Country Comparative Statistical Analysis (ANOVA / Chi-Square).",
        "conclusion": "Remediation advice is severely lacking globally, with presence ranging from 37% to 77%. Significant geopolitical disparities exist: websites in the Global South (particularly Africa and Oceania) offer significantly less remediation guidance and fewer robust authentication recovery options (relying almost solely on basic email verification without MFA).",
        "further_areas_research": "Investigating remediation disparities between desktop web platforms and native mobile apps; evaluating usability of remediation workflows through end-user cognitive walkthroughs; assessing the adoption of standardized remediation protocols (e.g., RFC 8882)."
    },
    {
        "doc_name": "2302.13261v1.pdf",
        "title": "SoK: Evaluating Privacy and Security Concerns of Using Web Services for the Disabled Population",
        "year": "2023",
        "aim": "To systematize knowledge regarding the privacy and security challenges faced by disabled individuals navigating modern web services, focusing on authentication barriers, accessibility standards, and inclusive design paradigms.",
        "objectives": "1. Synthesize peer-reviewed literature at the intersection of disability accessibility and web security/privacy.\n2. Examine usability failures of standard authentication mechanisms (e.g., CAPTCHAs, MFA) for disabled users.\n3. Propose guidelines for universal, accessible, and privacy-preserving web architectures.",
        "research_questions": "RQ1: What are the privacy and security concerns related to the disabled community when interacting with web services?\nRQ2: How can CAPTCHAs/authentication be improved to protect the privacy and security of people with disabilities?\nRQ3: How can universal design and inclusive privacy/security be implemented in web services?",
        "methodology": "Systematization of Knowledge (SoK) using a Systematic Literature Review of N=63 peer-reviewed articles selected through multi-database querying (ACM, IEEE, Google Scholar), multi-phase screening (title, abstract, full-text), and thematic synthesis across 6 primary themes.",
        "model_used": "PRISMA-guided Systematic Literature Review; Thematic Analysis; Universal Design / WCAG Accessibility Framework.",
        "conclusion": "A severe disparity exists at the intersection of security and disability: security controls (especially visual CAPTCHAs and rigid multi-factor schemes) disproportionately disenfranchise disabled individuals. Privacy concerns are heightened due to reliance on assistive tech and third-party caregivers, which often leak sensitive data or require credential sharing.",
        "further_areas_research": "Empirical co-design of multi-modal biometric and audio-tactile authentication interfaces; automated accessibility auditing tools specifically checking security and privacy dialogs; development of privacy frameworks for assistive devices and smart home health technology."
    },
    {
        "doc_name": "2306.06033v3.pdf",
        "title": "SoK: Analysis of User-Centered Studies Focusing on Healthcare Privacy & Security",
        "year": "2023",
        "aim": "To synthesize empirical user-centered research in healthcare data privacy and security to understand user perceptions, behaviors, and vulnerabilities regarding protected health information.",
        "objectives": "1. Systematically review user studies addressing patient and practitioner healthcare data privacy/security.\n2. Identify core recurring themes and discourse gaps using card sorting.\n3. Develop recommendations for human-centered healthcare security interventions.",
        "research_questions": "RQ1: How do user-centered studies examine privacy and security risks in healthcare contexts?\nRQ2: What key themes characterize user interactions with protected health information, and what critical demographic or contextual gaps remain?",
        "methodology": "Systematic Literature Review across 7 digital repositories (ACM DL, Google Scholar, SSRN, ScienceDirect, IEEE Xplore, PubMed, MEDLINE) resulting in N=129 candidate papers and n=26 focused user-study papers. Conducted an open and closed card-sorting exercise with researchers to extract and structure 12 thematic clusters.",
        "model_used": "Card Sorting Methodology; Qualitative Thematic Synthesis; Systematic Literature Review (SLR) Protocol.",
        "conclusion": "The analysis identified 12 core themes (including Data Sharing, Risk Awareness, Privacy, Regulatory Compliance). Research heavily concentrates on patient willingness to share data and portal access, while neglecting vulnerable subgroups (pediatric, geriatric, disabled patients), clinical workflow constraints, and practitioner burden in maintaining compliance.",
        "further_areas_research": "Investigating healthcare privacy decision-making under acute cognitive/emotional distress; designing privacy-preserving health wearable interfaces; evaluating usable security tools tailored for frontline clinical staff."
    },
    {
        "doc_name": "2312.14633v1.pdf",
        "title": "Evaluating the Security and Privacy Risk Postures of Virtual Assistants",
        "year": "2023",
        "aim": "To quantitatively evaluate the technical security vulnerabilities, permissions architecture, and privacy leakage risks across leading commercial and open-source virtual voice assistants (VAs).",
        "objectives": "1. Conduct static code and binary vulnerability analysis across 8 major virtual assistants.\n2. Evaluate requested permissions, attack surfaces, and third-party tracking libraries.\n3. Identify insecure cryptographic implementations and sensitive data handling practices.",
        "research_questions": "RQ1: What latent security vulnerabilities and architectural flaws exist within widely deployed voice assistants?\nRQ2: To what extent do voice assistants request over-privileged permissions and integrate third-party tracking components that compromise user privacy?",
        "methodology": "Multi-tool automated static security audit and permission inspection across 8 Android-based virtual assistants: Alexa, Braina, Cortana, Google Assistant, Kalliope, Mycroft, Hound, and Extreme. Assessed five security domains: code quality, access control, tracking, binary analysis, and sensitive data confidentiality.",
        "model_used": "Static Application Security Testing (SAST) using AndroBugs Framework, MobSF (Mobile Security Framework), RiskInDroid, Permission Over-privilege Analysis.",
        "conclusion": "Virtual assistants are riddled with critical security vulnerabilities: failure to validate SSL certificates, execution of raw SQL queries vulnerable to injection, reliance on weak AES encryption modes (e.g., AES-ECB), extensive over-privileged permissions (especially microphone and location), and widespread third-party tracking integrations.",
        "further_areas_research": "Dynamic runtime analysis and network traffic inspection; hardware-level and firmware auditing on dedicated smart speaker hardware; extending evaluations to iOS voice assistants and LLM-powered embodied agents."
    },
    {
        "doc_name": "2407.05450v1.pdf",
        "title": "Understanding Professional Needs to Create Privacy-Preserving and Secure Emergent Digital Artworks",
        "year": "2024",
        "aim": "To explore how interactive and emergent digital art installations handle audience surveillance and data capture, and identify the tools, guidelines, and frameworks media artists and cybersecurity experts need to design privacy-preserving immersive art.",
        "objectives": "1. Investigate current data collection practices in immersive art installations (cameras, depth sensors, biometric trackers).\n2. Identify practitioner needs and technical knowledge gaps regarding security and privacy.\n3. Formulate a set of privacy parameters to guide development of secure media arts software.",
        "research_questions": "RQ1: How do media artists and cybersecurity practitioners perceive the privacy and security risks associated with data-gathering immersive artworks?\nRQ2: What technical, conceptual, and regulatory parameters are needed to support the creation of privacy-preserving interactive installations?",
        "methodology": "Qualitative pilot study employing semi-structured in-depth interviews with 5 senior practitioners (2 interactive media artists and 3 cybersecurity experts). Conducted qualitative thematic coding to extract key operational parameters.",
        "model_used": "Semi-Structured Qualitative Interviewing; Thematic Content Analysis; Privacy-Preserving Parameter Extraction Model.",
        "conclusion": "Media artists actively collect rich biometric, kinetic, and spatial participant data but lack formal cybersecurity knowledge and threat modeling tools. Practitioners strongly advocate for transparent opt-in mechanics, minimal data storage, and using immersive art itself as an experiential medium for public privacy education.",
        "further_areas_research": "Developing and testing an open-source, privacy-preserving software SDK for media artists; conducting audience user studies during live interactive art exhibitions to evaluate privacy perception; evaluating real-time anonymization algorithms for sensory art pipelines."
    },
    {
        "doc_name": "2410.08555v2.pdf",
        "title": "Design of Secure, Privacy-focused, and Accessible E-Payment Applications for Older Adults",
        "year": "2024",
        "aim": "To design, prototype, and empirically evaluate a secure, privacy-preserving, and accessible mobile electronic payment application tailored specifically to the functional needs and preferences of older adults (aged 60+).",
        "objectives": "1. Develop a high-fidelity e-payment prototype integrating co-design findings.\n2. Conduct an empirical evaluation with 400 older adults.\n3. Assess preferences regarding authentication modes (MFA vs single-mode), QR-code interactions, and privacy disclosures.",
        "research_questions": "RQ1: How do older adults perceive and interact with security and privacy features in mobile e-payment applications?\nRQ2: Which authentication mechanisms and UI adaptations best reconcile security rigor with older adult accessibility and usability?",
        "methodology": "Quantitative and qualitative survey-based user study with N=400 older adults (≥60 years) evaluating an interactive high-fidelity mobile prototype with features like MFA, QR-code recipient adding, and privacy settings, followed by iterative refinement into a beta-version.",
        "model_used": "High-Fidelity Prototyping (Figma); Usability & Accessibility Evaluation (WCAG 2.1); Descriptive/Inferential Survey Analysis.",
        "conclusion": "91% of older adults overwhelmingly preferred traditional knowledge-based, single-mode authentication (passwords/PINs) over expert-recommended MFA due to complexity and cognitive load. Older adults demand transparent transaction summaries, simplified confirmation flows, and accessible visual design.",
        "further_areas_research": "Real-world transactional field trials of the beta application; evaluating accessible multi-modal biometric authentication (voice/fingerprint); designing educational interventions that increase trust in MFA among aging users."
    },
    {
        "doc_name": "2410.14924v1.pdf",
        "title": "Securing the Web: Analysis of HTTP Security Headers in Popular Global Websites",
        "year": "2024",
        "aim": "To provide a large-scale empirical audit of the implementation, compliance, and strength of HTTP security headers across the world's most visited websites across diverse industry categories.",
        "objectives": "1. Categorize top global websites into functional domains using NLP.\n2. Evaluate implementation of 12 critical HTTP security headers (HSTS, CSP, X-Frame-Options, SRI, etc.) using automated scanning.\n3. Quantify security score disparities across industry sectors (e-commerce, banking, healthcare, government).",
        "research_questions": "RQ1: To what extent do globally popular websites implement and adhere to recommended HTTP security headers?\nRQ2: How do HTTP security header postures differ across various website categories, particularly critical sectors like healthcare and finance?",
        "methodology": "Large-scale empirical scanning of N=3,195 websites selected from the top 10,000 Tranco list. Applied Google Cloud NLP for automated categorization into 27 functional sectors (validated via Symantec Sitereview). Conducted automated header evaluation using Mozilla Observatory CLI across 12 security header rules.",
        "model_used": "Google NLP API Categorization; Mozilla Observatory Automated Security Scoring Engine; Cross-Category Statistical ANOVA/Kruskal-Wallis Evaluation.",
        "conclusion": "Over half of the websites examined (55.66%) failed the audit with a dismal grade of 'F'. Critical headers such as Content Security Policy (CSP), HTTP Strict Transport Security (HSTS), and Subresource Integrity (SRI) are heavily neglected. Alarmingly, healthcare websites (n=59) scored the lowest average score (18.14/100) despite managing sensitive patient data.",
        "further_areas_research": "Scaling the evaluation across the entire 1M Tranco list; assessing developer perceptions and technical obstacles to header configuration; auditing cookie security attributes and runtime tracking scripts alongside headers."
    },
    {
        "doc_name": "2506.04659v1.pdf",
        "title": "Multi-Tool Analysis of User Interface & Accessibility in Deployed Web-Based Chatbots",
        "year": "2025",
        "aim": "To conduct a comprehensive multi-tool diagnostic evaluation of the user interface quality, accessibility adherence, and performance standards of deployed web-based conversational agents.",
        "objectives": "1. Evaluate 106 live, deployed web chatbots across healthcare, education, customer service, and e-commerce.\n2. Compare automated accessibility tools against manual inspection standards.\n3. Identify systemic WCAG violations and formulate design recommendations for accessible conversational UI.",
        "research_questions": "RQ1: What are the prevalent accessibility and usability violations in modern deployed web chatbots?\nRQ2: How well do leading automated accessibility auditing tools correlate in identifying chatbot UI defects?",
        "methodology": "Dual-mode auditing of N=106 deployed web-based chatbots (standalone and embedded widgets). Used automated tools (Google Lighthouse, PageSpeed Insights, SiteImprove Accessibility Checker) combined with manual accessibility inspections using Microsoft Accessibility Insights across WCAG 2.1 AA criteria.",
        "model_used": "WCAG 2.1 Accessibility Diagnostic Model; Multi-Tool Correlation Analysis (Pearson's r); Automated Lighthouse/PageSpeed Auditing.",
        "conclusion": "Over 80% of deployed chatbots have critical accessibility defects, and 45% suffer from broken semantic structures or ARIA role misuses that render them unusable with screen readers. While accessibility scores correlated strongly between tools (r = 0.861), performance scores did not (r = 0.436), proving single-tool audits are insufficient.",
        "further_areas_research": "Extending accessibility audits to native mobile app chatbots and multimodal voice interfaces; conducting longitudinal user testing with disabled individuals using assistive tech; creating automated accessibility linters for chatbot widget SDKs."
    },
    {
        "doc_name": "2510.12031v1.pdf",
        "title": "Security and Privacy Assessment of U.S. and Non-U.S. Android E-Commerce Applications",
        "year": "2025",
        "aim": "To assess and compare the software security postures, cryptographic robustness, and privacy permission practices of top-grossing Android e-commerce mobile applications between the U.S. and international markets.",
        "objectives": "1. Audit 92 popular e-commerce Android apps (58 U.S. and 34 non-U.S.).\n2. Evaluate vulnerabilities in code, manifests, SSL/TLS, and network configurations.\n3. Assess regional differences in privacy compliance under GDPR and CCPA.",
        "research_questions": "RQ1: How does the security robustness of leading e-commerce mobile applications vary by major market region (U.S. vs. non-U.S.)?\nRQ2: How do differences in privacy measures reflect the regional privacy regulations governing these applications?",
        "methodology": "Static application security testing (SAST) and privacy analysis of N=92 top-grossing Android e-commerce apps (58 U.S., 34 non-U.S.) downloaded from Google Play Store. Evaluated using MobSF, AndroBugs, and RiskInDroid across manifest analysis, code vulnerabilities, certificate validation, and permission profiling.",
        "model_used": "Mobile Security Framework (MobSF); AndroBugs 2 Scanner; RiskInDroid Permission Risk Classifier; Comparative Regional Hypothesis Testing (Mann-Whitney U).",
        "conclusion": "Widespread security and privacy vulnerabilities persist globally: ~92% of apps utilized insecure HTTP traffic, average MobSF score was an alarming 40.92/100, and 77 apps had over-privileged permissions. U.S. apps performed slightly better with fewer manifest and code flaws, while EU apps exhibited more 'ghost permissions' despite GDPR.",
        "further_areas_research": "Dynamic runtime and network traffic analysis during live transactions; expanding auditing to iOS e-commerce applications; evaluating how third-party payment gateways and trackers process financial data."
    },
    {
        "doc_name": "2512.15945v1.pdf",
        "title": "Privacy Discourse and Emotional Dynamics in Mental Health Information Interaction on Reddit",
        "year": "2025",
        "aim": "To quantify the relationship between user emotional sentiment and privacy discussions within online mental health peer-support communities on Reddit.",
        "objectives": "1. Scrape and assemble a large-scale corpus of mental health and regulatory Reddit discourse.\n2. Apply sentiment analysis and semantic cosine similarity to measure emotional alignment across subreddits.\n3. Perform temporal trend analysis of privacy and regulatory awareness (HIPAA, GDPR) from 2020 to 2025.",
        "research_questions": "RQ1: How do privacy concerns manifest across diverse mental health peer-support communities on Reddit?\nRQ2: How does user sentiment correlate with discussions of privacy risks and regulatory events over time?",
        "methodology": "Computational text-mining and discourse analysis across 14 subreddits (10,119 posts, 65,385 comments) collected via custom web scraper spanning 2020–2025. Conducted lexicon-based sentiment analysis, sentiment vector cosine similarity, and keyword dictionary tagging for privacy/regulations (HIPAA, GDPR).",
        "model_used": "Lexicon-Based Sentiment Analysis; Cosine Similarity of Sentiment Distributions; Chi-Square Test of Independence (χ² = 5596.67, p=0.03); Temporal Keyword Frequency Modeling.",
        "conclusion": "Privacy discussions increased by 50% from 2020 to 2025, driven by regulatory changes and privacy breaches. Emotional distributions aligned closely between related disorders (Bipolar & ADHD: 0.877; Anxiety & Depression: 0.849). Discussions of health privacy strongly co-occur with heightened negative sentiment and vulnerability.",
        "further_areas_research": "Machine learning-based aspect-level sentiment classification; cross-platform validation (Discord, support forums); investigating the impact of LLM integration into mental health platforms on user privacy perceptions."
    },
    {
        "doc_name": "2602.15866v1 (1).pdf",
        "title": "NLP Privacy Risk Identification in Social Media (NLP-PRISM): A Survey",
        "year": "2026",
        "aim": "To systematically characterize and identify privacy risks, vulnerabilities, and mitigation strategies across major Natural Language Processing (NLP) tasks applied to social media data.",
        "objectives": "1. Formulate the NLP-PRISM evaluation framework spanning six vulnerability dimensions.\n2. Conduct an exhaustive survey of 203 peer-reviewed studies across six core NLP tasks.\n3. Quantify utility-privacy trade-offs under privacy-preserving fine-tuning (DP, FL).",
        "research_questions": "RQ: What specific privacy risks emerge when key NLP tasks (sentiment analysis, emotion detection, offensive language identification, code-mixed text processing, native language identification, dialect detection) are applied to social media data?",
        "methodology": "Comprehensive systematic survey reviewing 3,982 papers and filtering down to N=203 peer-reviewed studies. Evaluated attack vulnerabilities including Membership Inference Attacks (MIA), Attribute Inference Attacks (AIA), training data memorization, and fairness/bias distortions across transformer architectures (BERT, RoBERTa, LLaMA).",
        "model_used": "NLP-PRISM Framework; Transformer architectures (BERT, RoBERTa); Membership Inference Attacks (MIA AUC); Attribute Inference Attacks (AIA); Differential Privacy (DP); Federated Learning (FL); SHAP/LIME explainability.",
        "conclusion": "Transformers achieve strong task performance (F1: 0.58–0.84) but leak sensitive personal attributes (AIA accuracy 0.75, MIA AUC 0.81). Applying privacy-preserving mechanisms (e.g. DP) causes a 1%–23% drop in F1-score and a 2%–9% utility penalty. Significant research gaps exist in code-mixed and non-English social media privacy defenses.",
        "further_areas_research": "Developing adaptive differential privacy budgets for informal and multilingual text; benchmarking privacy-utility trade-offs in Large Language Models (LLMs); creating standardized automated privacy vulnerability auditing benchmarks for social media NLP pipelines."
    },
    {
        "doc_name": "2602.15866v1.pdf",
        "title": "NLP Privacy Risk Identification in Social Media (NLP-PRISM): A Survey (Duplicate)",
        "year": "2026",
        "aim": "To systematically characterize and identify privacy risks, vulnerabilities, and mitigation strategies across major Natural Language Processing (NLP) tasks applied to social media data (Identical duplicate of 2602.15866v1 (1).pdf).",
        "objectives": "1. Formulate the NLP-PRISM evaluation framework spanning six vulnerability dimensions.\n2. Conduct an exhaustive survey of 203 peer-reviewed studies across six core NLP tasks.\n3. Quantify utility-privacy trade-offs under privacy-preserving fine-tuning.",
        "research_questions": "RQ: What specific privacy risks emerge when key NLP tasks are applied to social media data, where models inadvertently reveal or infer sensitive personal attributes?",
        "methodology": "Comprehensive systematic survey reviewing 3,982 papers and filtering down to N=203 peer-reviewed studies. Evaluated attack vulnerabilities including Membership Inference Attacks (MIA), Attribute Inference Attacks (AIA), and training data memorization.",
        "model_used": "NLP-PRISM Framework; Transformer architectures; Differential Privacy; Federated Learning; Membership & Attribute Inference Attack Models.",
        "conclusion": "Transformers leak sensitive personal attributes (AIA accuracy 0.75, MIA AUC 0.81). Applying differential privacy causes a 1%–23% drop in F1-score and utility penalties.",
        "further_areas_research": "Adaptive differential privacy budgets for multilingual text; benchmarking privacy-utility trade-offs in LLMs; standardized automated privacy auditing benchmarks."
    },
    {
        "doc_name": "3190619.3191682.pdf",
        "title": "Poster: Understanding Privacy Concerns of WhatsApp Users in India",
        "year": "2018",
        "aim": "To investigate the risk perceptions, privacy feature usage, and behavioral controls of Indian WhatsApp users on mobile messaging platforms.",
        "objectives": "1. Survey Indian WhatsApp users regarding specific privacy controls (Last Seen, Read Receipts, Live Location, Profile Picture).\n2. Evaluate user attitudes toward targeted ads, data sharing, and unsolicited group additions.\n3. Propose actionable design and policy recommendations for mobile instant messaging (MIM).",
        "research_questions": "RQ: How do WhatsApp users in India perceive and utilize privacy settings, and what privacy concerns emerge regarding feature defaults, data sharing, and group dynamics?",
        "methodology": "Empirical survey-based user study with N=213 Indian WhatsApp users evaluating privacy attitudes, feature adoption rates, and contact-sharing behaviors.",
        "model_used": "Descriptive & Frequency Statistics; Cross-Tabulation; Usable Privacy Evaluation Framework.",
        "conclusion": "73.24% of users actively used the blocking feature, while Live Location was least utilized (27.91%). 90.57% kept Read Receipts enabled and 63.46% displayed their profile pictures, revealing feature-specific risk thresholds. Users strongly objected to being added to groups without consent and feared commercial data exploitation.",
        "further_areas_research": "Designing granular, context-aware group invitation permissions; evaluating automated privacy nudges for chat messaging; conducting cross-cultural comparisons of messaging privacy behaviors."
    },
    {
        "doc_name": "3290605.3300698.pdf",
        "title": "Techies Against Facebook: Understanding Negative Sentiment Toward Facebook via User Generated Content",
        "year": "2019",
        "aim": "To uncover the underlying factors and drivers behind negative sentiment and non-use practices toward social media platforms (specifically Facebook) among technically savvy users.",
        "objectives": "1. Gather and analyze naturalistic, unsolicited reader comments on tech-focused platforms (Slashdot and Schneier on Security).\n2. Conduct rigorous qualitative coding to categorize drivers of negative sentiment.\n3. Map the relationship between negative sentiment, privacy violations, and technology non-use behaviors.",
        "research_questions": "RQ: What factors lead technically savvy individuals to hold negative views toward social media services?",
        "methodology": "Naturalistic computational and qualitative text analysis of N=3,000 user comments extracted from Facebook-related discussions on two technology blogs (Slashdot and Schneier on Security) spanning multiple years, utilizing iterative inductive coding and sentiment classification.",
        "model_used": "Inductive Thematic Qualitative Coding; Inter-Rater Reliability (Cohen's Kappa); Technology Acceptance Model (TAM/Non-Use Framework).",
        "conclusion": "Nearly 45% of reader comments expressed explicit negative sentiment. Three primary pillars drive negative sentiment: (1) Privacy and Security (behavioral tracking, third-party data sharing, lack of control); (2) User Experience (manipulative algorithms, low-quality content, platform lock-in); and (3) Personal Disposition (philosophical rejection of surveillance capitalism, ethical concerns). Negative sentiment acts as an explicit precursor to complete or partial non-use.",
        "further_areas_research": "Examining whether negative sentiment and non-use practices among tech-savvy users diffuse to mainstream non-technical user populations; analyzing negative sentiment dynamics on newer decentralized or alternative social platforms; evaluating long-term user off-boarding and data deletion experiences."
    },
    {
        "doc_name": "3293578.3293589.pdf",
        "title": "Modularity is the Key: A New Approach to Social Media Privacy Policies",
        "year": "2019",
        "aim": "To address the failure of monolithic, all-or-nothing social media privacy policies by proposing a Modularized Privacy Policy Model (MPPM) that aligns policy agreements directly with specific platform functionalities.",
        "objectives": "1. Critique the readability and binary take-it-or-leave-it nature of social media privacy policies (focusing on Facebook).\n2. Conceptualize and design the Modularized Privacy Policy Model (MPPM).\n3. Establish a service-policy mapping framework that permits users to opt into specific features while preserving data minimization.",
        "research_questions": "RQ1: How can social media privacy policies be structured to overcome the all-or-nothing consent dilemma?\nRQ2: Does modularizing policy statements based on discrete functional services improve user autonomy and enforce data minimization?",
        "methodology": "Conceptual architectural design, usability modeling, and structural policy decomposition of Facebook's privacy policy, mapping legal clauses to individual services (e.g., photo sharing, location check-in, messaging).",
        "model_used": "Modularized Privacy Policy Model (MPPM); Service-Policy Mapping Matrix; Data Minimization and Privacy-by-Design Framework.",
        "conclusion": "Monolithic privacy policies force users into an unfair trade-off between total consent and service exclusion. The MPPM enables users to select specific service modules, denying data collection for unused features without forfeiting the entire application, while providing developers with a streamlined compliance mapping framework.",
        "further_areas_research": "Conducting empirical user testing and controlled lab trials of the MPPM interactive interface; evaluating legal enforceability under GDPR/CCPA; measuring the cognitive load of modular privacy consent compared to standard policies."
    },
    {
        "doc_name": "3710913.pdf",
        "title": "Social Media Misinformation and Voting Intentions: Older Adults' Experiences with Manipulative Narratives",
        "year": "2025",
        "aim": "To investigate how older adults conceptualize, discern, and contextualize political misinformation on social media, specifically examining the interplay between voting intentions and cognitive discernment strategies.",
        "objectives": "1. Survey older adults (n=119) and interview a subset (n=21) regarding encounters with election misinformation.\n2. Analyze differences in perceived misinformation purpose based on political alignment (Democrat vs. Republican).\n3. Identify cognitive heuristics, analytical thinking, and verification mechanisms older adults employ to assess narrative truthfulness.",
        "research_questions": "RQ1: How do older adults in America conceptualize and discern social media misinformation during election cycles?\nRQ2: How do political leanings and voting intentions influence perceptions of manipulative intent and truth verification strategies?",
        "methodology": "Mixed-methods empirical study combining an online quantitative survey (n=119 older adults aged 60+) with in-depth semi-structured qualitative interviews (n=21). Applied rigorous codebook-based thematic analysis, chi-square tests, and cross-tabulation.",
        "model_used": "Dual-Process Cognitive Theory (Heuristics vs. Analytical Thinking); Qualitative Thematic Codebook Analysis; Chi-Square Contingency Analysis.",
        "conclusion": "Older adults are not passive victims of fake news; they actively deploy analytical fact-checking and source heuristics. Marked partisan divergence emerged: 62% of Democrat voters perceived manipulative political motives behind misinformation versus 5% of Republicans. 74% of Democrats expressed severe alarm over misinformation escalating political extremism, whereas Republicans framed misinformation primarily as a reflection of media bias and free speech tension.",
        "further_areas_research": "Evaluating the effectiveness of targeted digital media literacy and cognitive debiasing interventions for aging citizens; longitudinal tracking of older adult political sharing behavior during active election cycles; studying the role of generative AI deepfakes in swaying older voter perceptions."
    },
    {
        "doc_name": "3734477.3736146.pdf",
        "title": "POSTER: VeilPIR: A Lightweight Private Information Retrieval Protocol for Enhancing Data Privacy in IoT Ecosystems",
        "year": "2025",
        "aim": "To design, implement, and benchmark a lightweight single-server Private Information Retrieval (PIR) protocol tailored for resource-constrained, low-power IoT sensor devices.",
        "objectives": "1. Overcome the extreme computational and memory overhead of existing homomorphic encryption/PIR schemes.\n2. Develop VeilPIR, shifting heavy cryptographic computation to untrusted servers while keeping client operations minimal.\n3. Implement and empirically evaluate VeilPIR under simulated IoT wireless conditions (BLE, Wi-Fi).",
        "research_questions": "RQ: How can a single-server Private Information Retrieval protocol achieve semantic query privacy on ultra-low-power microcontrollers while maintaining sub-second query latency and sub-Joule energy consumption?",
        "methodology": "Cryptographic protocol design and systems implementation in Python/Flask. Tested on simulated IoT microcontroller client and cloud server across database sizes ranging from 10 to 1,000 records. Evaluated round-trip time (RTT), ciphertext payload size, and energy consumption per query.",
        "model_used": "Lightweight Single-Server Additive Homomorphic Cryptosystem; One-Hot Query Vector Encoding; Semantic Privacy Model; Benchmark Performance Profiling.",
        "conclusion": "VeilPIR achieved a 900 ms round-trip time for 1,000 database records with energy consumption strictly below 1 Joule per query on IoT clients. The protocol supports live database record insertions and deletions without requiring complete database re-encryption.",
        "further_areas_research": "Hardware implementation on physical embedded ARM Cortex-M/ESP32 microcontrollers; optimizing multi-query batching over constrained BLE meshes; scaling to databases with tens of thousands of IoT telemetry records."
    },
    {
        "doc_name": "3770762.3772628.pdf",
        "title": "Starting with DEI and Ethics - A New First-Year College Computer Science Introduction",
        "year": "2026",
        "aim": "To restructure introductory undergraduate computer science education by embedding Diversity, Equity, Inclusion (DEI) and ethical reasoning from day one in a required first-year course.",
        "objectives": "1. Design and deploy an 18-session discussion-based introductory CS course running concurrently with programming.\n2. Dedicate 5 full modules to computing ethics, algorithmic bias, systemic inequality, and DEI.\n3. Empirically assess longitudinal student shifts in attitudes, awareness, and sense of belonging over 3 academic years.",
        "research_questions": "RQ1: How does early, integrated instruction in DEI and ethics impact first-year computer science students' awareness of societal harms in computing?\nRQ2: Does early exposure to inclusive computing foster a stronger sense of belonging among historically underrepresented students?",
        "methodology": "Longitudinal quasi-experimental educational intervention conducted across three consecutive academic years (2022–2024) at the University of Denver. Evaluated pre-course and post-course survey data from N=451 undergraduate CS students using validated psychological scales of belonging and ethical reasoning.",
        "model_used": "Pre/Post Survey Quantitative Analysis; Longitudinal Cohort Tracking; Culturally Responsive Computing Education Framework; Sense of Belonging Likert Scales.",
        "conclusion": "Early integration of ethics and DEI significantly elevated students' awareness of algorithmic bias and societal impacts without detracting from core technical preparation. Underrepresented students reported higher self-efficacy, increased retention, and a measurably stronger sense of departmental belonging.",
        "further_areas_research": "Tracking student retention, senior capstone ethical awareness, and industry hiring trajectories longitudinally; adapting the DEI/ethics curriculum modules to diverse institutional contexts (community colleges, large research universities); integrating hands-on AI fairness auditing labs into the syllabus."
    },
    {
        "doc_name": "frai-05-976838.pdf",
        "title": "Exploring gender biases in ML and AI academic research through systematic literature review",
        "year": "2022",
        "aim": "To systematically analyze how gender bias manifests, is detected, and is mitigated across academic machine learning and artificial intelligence literature.",
        "objectives": "1. Execute a systematic review of peer-reviewed AI/ML literature on gender bias.\n2. Categorize bias manifestations across NLP, computer vision, recommendation systems, and automated decision-making.\n3. Synthesize state-of-the-art debiasing techniques and formulate an end-to-end fairness framework.",
        "research_questions": "RQ1: How is gender bias defined, identified, and measured across different subfields of AI and machine learning?\nRQ2: What algorithmic debiasing methods exist across data, model, and post-processing stages, and what are their limitations?",
        "methodology": "Systematic Literature Review (SLR) querying major databases (IEEE Xplore, ACM DL, Google Scholar, ScienceDirect, SpringerLink). Screened and analyzed peer-reviewed studies published between 2010 and 2022, extracting data representations, evaluation metrics, and bias mitigation methodologies.",
        "model_used": "PRISMA Systematic Review Protocol; Algorithmic Fairness Framework; Metric Categorization (Disparate Impact, Equalized Odds, Word Embedding Association Test - WEAT).",
        "conclusion": "Gender bias is deeply embedded across multimodal AI pipelines—from toxic training dataset stereotypes and biased word embeddings in NLP to facial recognition inaccuracies for women of color. Current debiasing methods often sacrifice model utility or fail to generalize outside benchmark datasets.",
        "further_areas_research": "Intersectionality-aware debiasing algorithms (accounting for gender, race, and age simultaneously); dynamic bias mitigation in large-scale generative foundation models and multimodal systems; establishing standardized, auditable fairness benchmarks for commercial AI deployments."
    },
    {
        "doc_name": "ssrn-3438178.pdf",
        "title": "Towards Implementing Inclusive Authentication Technologies for Older Adults",
        "year": "2019",
        "aim": "To investigate the usability barriers, mental models, and adoption challenges of modern Two-Factor Authentication (2FA) technologies—specifically hardware security keys—among older adults.",
        "objectives": "1. Evaluate older adults' interaction with FIDO U2F Yubico Security Keys.\n2. Identify physical, cognitive, and procedural halt points during key setup and daily usage.\n3. Develop inclusive authentication guidelines for organizations safeguarding older adults' assets.",
        "research_questions": "RQ1: What specific usability and cognitive hurdles prevent older adults from adopting hardware security tokens?\nRQ2: How can 2FA hardware and verification workflows be redesigned to accommodate aging sensory and cognitive faculties?",
        "methodology": "Qualitative usability study involving N=10 older adults (>60 years) using pre-surveys, think-aloud protocol during registration/setup of Yubico FIDO U2F keys, semi-structured interviews, and follow-up usability evaluations.",
        "model_used": "Think-Aloud Protocol; Cognitive Usability Walkthrough; Thematic Analysis; Usable Security Evaluation Framework.",
        "conclusion": "Older adults face a negative feedback loop: lack of inclusive design (tiny form factors, obscure USB-A/C ports, browser dependency, lack of visual/tactile feedback) causes frustration and non-adoption, leading vendors to neglect this demographic. Tangible benefits of 2FA are poorly communicated, causing elders to revert to insecure passwords.",
        "further_areas_research": "Designing multi-modal authentication tokens featuring haptic and auditory confirmation; evaluating passkey/biometric alternatives tailored for older adults; studying organizational assistance models within banks and healthcare portals."
    },
    {
        "doc_name": "ssrn-3443920.pdf",
        "title": "Smart Devices for Smart Cities in India: Exploring Security Vulnerabilities of E-Waste Management",
        "year": "2019",
        "aim": "To investigate the data security, privacy vulnerabilities, and hazardous electronic waste threats arising from the improper disposal, refurbishment, and second-hand trading of smart devices within India's emerging Smart Cities.",
        "objectives": "1. Assess the lifecycle and disposal pathways of smart devices (smartphones, tablets, smart toys) in urban India.\n2. Uncover personal data leakage vectors in informal second-hand markets.\n3. Formulate a sustainable, security-focused lifecycle framework for smart city e-waste.",
        "research_questions": "RQ1: What are possible security threats arising from smart devices in a smart city context?\nRQ2: What are the different issues and challenges associated with smart device e-waste management?\nRQ3: What is the role of the informal second-hand market in generating security and privacy threats from retired devices?",
        "methodology": "Mixed-methods study combining supply-chain lifecycle analysis with user and vendor interviews in informal second-hand electronics markets in Kolkata, India. Examined 3 device categories: smartphones, tablets, and smart toys.",
        "model_used": "Life Cycle Assessment (LCA) Framework; Reverse Engineering Vulnerability Analysis; Qualitative Field Interviewing; Supply-Chain Threat Modeling.",
        "conclusion": "The rapid influx of smart devices in Indian smart cities is feeding an unregulated informal second-hand market where devices are refurbished without data sanitization. Residual personal data (credentials, photos, financial records) is routinely extracted, while counterfeit component mixing compromises hardware integrity.",
        "further_areas_research": "Developing automated cryptographic data-wiping kiosks for informal e-waste hubs; integrating blockchain tracking into e-waste reverse supply chains; studying policy frameworks for formal certified recycling in developing economies."
    },
    {
        "doc_name": "ssrn-3443923.pdf",
        "title": "Study Exploring Security Threats in Waste Phones: A Lifecycle Based Approach",
        "year": "2019",
        "aim": "To analyze the security vulnerabilities, data exposure risks, and hardware attack vectors associated with discarded and end-of-life mobile phones (small WEEE) traversing informal recycling and refurbishment supply chains.",
        "objectives": "1. Map the supply chain of waste mobile phones from initial disposal through informal repair and second-hand resale.\n2. Identify technical attack vectors (chip-level, PCB-level, and software reverse engineering) used to recover residual user data.\n3. Develop a secure end-of-life device management model.",
        "research_questions": "RQ1: How does the informal supply chain of discarded mobile phones expose sensitive user data to malicious extraction?\nRQ2: What technical reverse engineering mechanisms are employed on waste phones, and how can lifecycle management mitigate these risks?",
        "methodology": "Comprehensive lifecycle analysis and technical threat modeling of mobile phone Waste Electrical and Electronic Equipment (WEEE). Examined hardware reverse engineering literature (chip-level, PCB stripping, software extraction) and evaluated informal recycling practices.",
        "model_used": "WEEE Lifecycle Threat Modeling; Reverse Engineering Analysis (Chip/PCB/System levels); Data Sanitization Assessment Framework.",
        "conclusion": "Conventional e-waste policies focus exclusively on environmental toxicity and precious metal recovery, completely ignoring data security. Less than 5% of mobile phones reach formal recyclers; the vast majority enter informal repair markets where simple software tools and chip-off forensics recover private credentials, emails, and photos.",
        "further_areas_research": "Hardware-enforced cryptographic self-destruct mechanisms triggered at device end-of-life; evaluating consumer attitudes toward secure phone disposal; standardizing certified data sanitization protocols for low-cost refurbishers."
    },
    {
        "doc_name": "ssrn-3445942.pdf",
        "title": "Privacy Preserving Policy Framework: User-Aware and User-Driven",
        "year": "2019",
        "aim": "To propose a user-aware, user-driven Privacy Preserving Policy Framework (P3F) that replaces take-it-or-leave-it online privacy policies with flexible, service-specific negotiation mechanisms.",
        "objectives": "1. Critically evaluate the structural and cognitive failures of monolithic privacy policies.\n2. Design a modular framework that decomposes policies into discrete functional services.\n3. Enable users to grant selective consent, enforcing data minimization while maintaining access to non-consented features.",
        "research_questions": "RQ1: How can privacy policies be transformed from passive legal notices into active, user-driven consent negotiations?\nRQ2: What technical architecture allows websites to dynamically restrict data collection based on granular user service selections?",
        "methodology": "Analytical policy modeling and architectural design. Deconstructed legal clauses from representative social media and e-commerce platforms, mapping each clause to functional web components, and establishing an operational framework for selective service gating.",
        "model_used": "Privacy-by-Design Architectural Framework; Service-Policy Decomposition Matrix; Selective Consent Gating Model.",
        "conclusion": "Monolithic binary consent invalidates meaningful privacy self-management. P3F empowers users to negotiate data exchange on an equal footing, ensuring that choosing not to share location or contacts only disables those specific features without locking users out of the core platform, strictly honoring data minimization.",
        "further_areas_research": "Implementation of P3F in live web frameworks (e.g., React, Django); evaluating user comprehension and satisfaction through controlled usability trials; analyzing legal alignment with GDPR Article 7 (conditions for consent) and CCPA."
    },
    {
        "doc_name": "ssrn-3534856.pdf",
        "title": "User-Centered Risk Communication for Safer Browsing",
        "year": "2020",
        "aim": "To design, deploy, and empirically evaluate a holistic, user-centered risk-management web browser tool that leverages metaphorical cartoon visualizations to enhance user risk perception and phishing defense.",
        "objectives": "1. Develop an integrated browser toolbar combining script blocking, tracker disabling, SSL warnings, and visual risk metaphors.\n2. Conduct a 4-week in-situ naturalistic trial measuring tool adoption and risk reduction.\n3. Test phishing detection efficacy under simulated real-world cognitive stress in a controlled laboratory experiment.",
        "research_questions": "RQ1: Is the holistic metaphorical risk management tool usable and acceptable to everyday users?\nRQ2: Do users interacting with the tool demonstrate significantly higher efficacy in detecting phishing sites?\nRQ3: How do acute cognitive stress conditions impact user risk behavior and mitigation tool efficacy?",
        "methodology": "Two-phase mixed-methods experimental evaluation. Phase 1: 4-week naturalistic longitudinal field deployment with control and experimental groups tracking live browser settings, script permissions, and unfamiliar site alerts. Phase 2: Controlled in-lab phishing detection trial with cognitive stress manipulation (time constraints, multitasking).",
        "model_used": "Mental Model Metaphorical Risk Framework; Longitudinal In-Situ Behavioral Tracking; Controlled Laboratory Factorial Design; Cognitive Stress Modeling.",
        "conclusion": "The metaphorical risk tool significantly improved safe browsing behaviors: longitudinal users ran fewer risky scripts, disabled iFrames, reduced tracking, and escalated safe habits weekly. In the lab, the tool dramatically boosted phishing detection rates, successfully maintaining user vigilance even under high cognitive stress conditions.",
        "further_areas_research": "Integrating machine-learning-driven adaptive metaphors; evaluating warning habituation over multi-month timeframes; extending the tool architecture to mobile web browsers and messaging applications."
    },
    {
        "doc_name": "ssrn-3669400.pdf",
        "title": "Change-Point Analysis of Cyberbullying-Related Twitter Discussions During COVID-19",
        "year": "2020",
        "aim": "To investigate the epidemiological surge in cyberbullying discourse on Twitter during the onset of the COVID-19 pandemic using statistical change-point analysis.",
        "objectives": "1. Collect and curate a comprehensive dataset of cyberbullying-related public tweets during the pandemic transition.\n2. Aggregate daily frequency counts across multiple cyberbullying and harassment keywords.\n3. Identify statistically significant structural breaks and change-points linked to global pandemic milestones.",
        "research_questions": "RQ: How do major societal crises, such as the COVID-19 global pandemic and associated lockdowns, impact the frequency and temporal dynamics of cyberbullying discussions on social media?",
        "methodology": "Quantitative time-series data mining and statistical modeling of N=454,046 public cyberbullying-related tweets collected between January 1, 2020, and June 7, 2020. Aggregated into daily time-series counts across specific cyberbullying keywords and applied change-point detection algorithms.",
        "model_used": "Statistical Change-Point Analysis (Pruned Exact Linear Time - PELT / Binary Segmentation); Time-Series Structural Break Modeling; Twitter Streaming API Mining.",
        "conclusion": "Statistically significant structural change-points were detected across almost all cyberbullying keywords, clustered predominantly in late March 2020. This timing directly corresponds with the declaration of national emergencies, school closures, and stay-at-home mandates, empirically linking social crisis confinement to heightened digital harassment discourse.",
        "further_areas_research": "Conducting aspect-based sentiment analysis and toxicity classification on tweet content surrounding detected change-points; examining cross-platform cyberbullying shifts (e.g., TikTok, Instagram); investigating demographic vulnerability variations across adolescents and remote workers."
    },
    {
        "doc_name": "ssrn-3669424 (1).pdf",
        "title": "Evaluating the Impact of COVID-19 on Cyberbullying through Bayesian Trend Analysis",
        "year": "2020",
        "aim": "To quantify the causal impact of COVID-19 lockdown interventions on the volume and trend of cyberbullying conversations on Twitter using Bayesian structural time-series modeling.",
        "objectives": "1. Mine longitudinal Twitter data spanning pre-pandemic and peak pandemic periods.\n2. Construct a synthetic counterfactual baseline of cyberbullying tweet volume.\n3. Measure the causal effect and posterior probability of pandemic-induced surges in online toxicity.",
        "research_questions": "RQ: Did the COVID-19 pandemic and stay-at-home orders cause a statistically significant, sustained increase in cyberbullying discussions on Twitter compared to a counterfactual non-pandemic scenario?",
        "methodology": "Advanced Bayesian causal inference on a longitudinal dataset of over 450,000 cyberbullying-related tweets (Jan–June 2020). Utilized daily frequency tracking across semantic keywords and built counterfactual projections using pre-lockdown historical trends.",
        "model_used": "Bayesian Structural Time Series (BSTS) Model; Markov Chain Monte Carlo (MCMC); CausalImpact Bayesian Estimation Framework.",
        "conclusion": "Bayesian causal analysis confirmed a statistically significant positive surge in cyberbullying discourse following stay-at-home orders (posterior tail-area probability p < 0.001). The relative increase in daily cyberbullying discussions exceeded 35% above the synthetic counterfactual baseline, persisting throughout the lockdown period.",
        "further_areas_research": "Applying Bayesian structural models to localized regional geographical sub-samples; analyzing topic modeling shifts within the cyberbullying corpus; developing automated real-time early warning algorithms for digital harassment spikes during public emergencies."
    },
    {
        "doc_name": "ssrn-3669424.pdf",
        "title": "Evaluating the Impact of COVID-19 on Cyberbullying through Bayesian Trend Analysis (Duplicate)",
        "year": "2020",
        "aim": "To quantify the causal impact of COVID-19 lockdown interventions on cyberbullying conversations on Twitter using Bayesian structural time-series modeling (Identical duplicate of ssrn-3669424 (1).pdf).",
        "objectives": "1. Mine longitudinal Twitter data spanning pre-pandemic and peak pandemic periods.\n2. Construct a synthetic counterfactual baseline of cyberbullying tweet volume.\n3. Measure the causal effect and posterior probability of pandemic-induced surges in online toxicity.",
        "research_questions": "RQ: Did the COVID-19 pandemic and stay-at-home orders cause a statistically significant increase in cyberbullying discussions on Twitter?",
        "methodology": "Advanced Bayesian causal inference on over 450,000 cyberbullying-related tweets (Jan–June 2020). Built counterfactual projections using pre-lockdown historical trends.",
        "model_used": "Bayesian Structural Time Series (BSTS) Model; Markov Chain Monte Carlo (MCMC); CausalImpact Bayesian Estimation Framework.",
        "conclusion": "Confirmed a statistically significant positive surge in cyberbullying discourse following stay-at-home orders (p < 0.001), exceeding 35% above the counterfactual baseline.",
        "further_areas_research": "Bayesian structural models for localized geographical sub-samples; topic modeling shifts within the corpus; real-time early warning algorithms for digital harassment."
    },
    {
        "doc_name": "ssrn-3875896.pdf",
        "title": "My Account Is Compromised — What Do I Do? Towards an Intercultural Analysis of Account Remediation",
        "year": "2021",
        "aim": "To formulate an intercultural, cross-national research agenda investigating how account remediation protocols and recovery advice vary across different linguistic, regulatory, and cultural web ecosystems.",
        "objectives": "1. Propose an intercultural framework for evaluating website account recovery and remediation advice.\n2. Identify cultural and linguistic biases in existing usable security remediation literature.\n3. Establish standardized evaluation metrics for cross-border account restoration audits.",
        "research_questions": "RQ: How do account compromise recovery instructions and technical remediation mechanisms differ across distinct global cultural, regional, and national web domains?",
        "methodology": "Conceptual framework development, pilot empirical website sampling, and intercultural comparative methodology design. Examined remediation guidance across multilingual portals in Europe, North America, and Asia.",
        "model_used": "Intercultural Usable Security Framework; 5-Phase Account Remediation Taxonomy; Comparative Qualitative Heuristic Evaluation.",
        "conclusion": "Account remediation advice is heavily Western-centric, with substantial translation deficiencies, missing localized guidance, and differing assumptions about user technical literacy and device ownership across cultural domains, leaving international users disproportionately vulnerable after compromises.",
        "further_areas_research": "Full-scale transcontinental empirical audits of popular global websites; user studies examining how cross-cultural mental models influence recovery success; development of standardized international account remediation guidelines."
    },
    {
        "doc_name": "ssrn-4084004.pdf",
        "title": "A Call for a New Privacy & Security Regime for IoT Smart Toys",
        "year": "2022",
        "aim": "To investigate the complex privacy, cybersecurity, and physical safety risks posed by Internet of Things (IoT) smart connected toys, and advocate for an updated regulatory and design governance regime to protect children and families.",
        "objectives": "1. Audit technical security vulnerabilities (unauthenticated Bluetooth, insecure Wi-Fi, unencrypted voice recordings) in commercial smart toys.\n2. Evaluate parent and caregiver mental models, threat awareness, and consent practices.\n3. Propose comprehensive regulatory updates to COPPA and GDPR and establish a dedicated IoT toy security standard.",
        "research_questions": "RQ1: What technical vulnerabilities exist in commercially available smart toys, and how do they expose children's private data and physical spaces?\nRQ2: How well do parents understand smart toy data collection practices, and how can policy frameworks better protect pediatric privacy?",
        "methodology": "Mixed-methods approach combining hardware/software vulnerability testing of popular smart toys (e.g., smart bears, connected dolls) with empirical parent surveys and an in-depth regulatory policy review of COPPA, GDPR-K, and FTC enforcement actions.",
        "model_used": "IoT Vulnerability Threat Modeling (STRIDE); Socio-Technical Privacy Risk Framework; Regulatory Policy Gap Analysis; Parental Mental Model Survey.",
        "conclusion": "Smart toys suffer from egregious security flaws: unauthenticated Bluetooth pairing allowing nearby eavesdroppers to speak directly to children, cloud storage leaks of children's voice recordings, and extensive third-party tracker integration. COPPA's notice-and-consent framework is fundamentally ill-equipped for conversational IoT toys that continuously record ambient audio.",
        "further_areas_research": "Developing hardware-based physical mute and camera shutters for smart toys; designing child-friendly, interactive privacy notifications; evaluating standardized IoT cybersecurity trust labels and certifications for parents."
    },
    {
        "doc_name": "ssrn-4173372.pdf",
        "title": "Security and Privacy Evaluation of Popular Augmented and Virtual Reality Technologies",
        "year": "2022",
        "aim": "To systematically evaluate the security and privacy postures of the 10 most popular commercial Augmented Reality (AR) and Virtual Reality (VR) hardware devices and consumer applications.",
        "objectives": "1. Audit 10 widely used AR/VR platforms across gaming, education, healthcare, and retail.\n2. Assess five critical dimensions: device authentication, user profiling, access control, database/cloud storage security, and sensory data capture.\n3. Highlight vulnerabilities and provide actionable engineering recommendations for immersive technologies.",
        "research_questions": "RQ: What are the prevailing security vulnerabilities and privacy leakages present in current generation commercial AR/VR devices and their associated software ecosystems?",
        "methodology": "Comprehensive multi-platform security audit and threat analysis of 10 prominent AR/VR platforms: Microsoft HoloLens, Meta Oculus, Google Glass, Valve Index, HTC Vive, Raptor AR, Psious (Amelia), Magic Leap, Epson Moverio, and IKEA Place AR. Evaluated authentication, sensor permissions, and data-in-transit encryption.",
        "model_used": "Systematic Architectural Security Evaluation; AR/VR Threat Vector Modeling; Permission & Sensor Profiling Analysis.",
        "conclusion": "Popular AR/VR platforms suffer from critical security shortcomings: lack of robust device authentication (frequently relying on simple PINs or no lock screen), extensive unconstrained sensor data capture (ambient spatial scanning, eye tracking, biometric telemetry), and opaque cloud synchronization with minimal user access controls.",
        "further_areas_research": "Designing privacy-preserving spatial computing APIs that blur bystanders and sensitive real-world objects; developing robust biometric authentication for VR headsets (e.g., iris, skull resonance); formulating privacy regulation standards specifically governing immersive spatial data."
    },
    {
        "doc_name": "ssrn-4230591.pdf",
        "title": "Understanding User Perspective in a University Setting to Improve Biometric Authentication Adoption",
        "year": "2022",
        "aim": "To evaluate user attitudes, usability experiences, and security/privacy concerns regarding biometric authentication on personal devices within a university student population to formulate adoption-enhancing design improvements.",
        "objectives": "1. Assess the prevalence of biometric authentication adoption (fingerprint, Face ID, voice/iris) among university students.\n2. Identify perceived security vulnerabilities, shoulder-surfing concerns, and false rejection issues.\n3. Develop user-centered design and security enhancements to bolster biometric adoption.",
        "research_questions": "RQ1: What are the primary motivators and usability barriers influencing university students' adoption of biometric authentication on personal smartphones?\nRQ2: What specific security and privacy concerns do users harbor regarding biometric access controls?",
        "methodology": "Empirical survey-based user study with N=38 university students evaluating daily lock-screen habits, technical experience, biometric modality usage (fingerprint, Face ID), shoulder-surfing protective behaviors, and fear of unauthorized account access.",
        "model_used": "Usable Security Assessment Model; Descriptive and Likert-Scale Survey Analysis; Behavioral Threat-Protection Index.",
        "conclusion": "Usability and unlocking speed are the overwhelming primary motivators for biometric adoption. However, significant user concerns persist regarding losing access to accounts, false recognition, and involuntary biometric unlock while asleep or under duress. 48.8% of users noted annoyance with unlocking failures in challenging conditions (masks, lighting).",
        "further_areas_research": "Evaluating dual-modality adaptive authentication (combining biometrics with contextual behavioral signals); studying biometric adoption and trust among non-student, older adult populations; developing anti-coercion unlock mechanisms."
    },
    {
        "doc_name": "ssrn-4474070.pdf",
        "title": "Privacy, Security, and Usability Tradeoffs of Telehealth from Practitioners' Perspectives",
        "year": "2023",
        "aim": "To investigate the complex trade-offs between cybersecurity, patient data privacy, system usability, and accessibility experienced by specialized medical practitioners using telehealth technologies post-COVID-19.",
        "objectives": "1. Conduct in-depth qualitative interviews with private practice audiologists and speech-language pathologists (SLPs).\n2. Identify operational hurdles in maintaining HIPAA compliance during remote therapy.\n3. Uncover practitioner challenges when delivering care to vulnerable populations (pediatric, geriatric, hearing-impaired).",
        "research_questions": "RQ: How do healthcare practitioners in allied fields (audiology and speech pathology) navigate the competing demands of data security, patient privacy, and clinical usability during telehealth sessions?",
        "methodology": "Qualitative empirical study consisting of N=20 semi-structured interviews with private telehealth practitioners (10 audiologists and 10 speech-language pathologists across the U.S. with at least two years of continuous telehealth experience). Analyzed via iterative thematic coding.",
        "model_used": "Qualitative Thematic Analysis; Socio-Technical Usable Security & Healthcare Compliance Trade-Off Model.",
        "conclusion": "Allied healthcare practitioners are deeply committed to patient privacy but lack the institutional IT support, financial resources, and technical training required to verify HIPAA compliance. Practitioners are forced to compromise security for usability, often utilizing commercial consumer video conferencing tools to ensure accessibility for older and disabled patients.",
        "further_areas_research": "Designing clinician-centered HIPAA verification and automated secure configuration tools; developing accessible telehealth platforms with built-in closed captioning and calibration tools for audiology; evaluating telehealth security practices in hospital-affiliated versus solo private practices."
    },
    {
        "doc_name": "ssrn-4825426.pdf",
        "title": "Assessing ChatGPT's Efficacy in Interpreting Privacy Policies",
        "year": "2024",
        "aim": "To quantitatively evaluate the efficacy of Large Language Models (specifically GPT-4) in simplifying, summarizing, and improving the reading accessibility of complex commercial website privacy policies.",
        "objectives": "1. Curate a benchmark corpus of 102 comprehensive privacy policies from leading global corporations across diverse industry sectors.\n2. Generate standardized plain-language interpretations using structured prompt engineering with ChatGPT-4.\n3. Statistically test readability score differences between original policies and AI interpretations using validated readability metrics.",
        "research_questions": "RQ: Can generative AI (ChatGPT-4) reliably transform dense, convoluted privacy policies into significantly more readable, accessible, and comprehendible documents for lay users?",
        "methodology": "Quantitative computational linguistics study analyzing N=102 corporate privacy policies (Amazon, Apple, Meta, Google, Microsoft, Walmart, etc.). Generated standardized summaries in ChatGPT-4 using structured multi-turn chunking prompts. Evaluated readability using the Flesch-Kincaid Grade Level and Reading Ease formulas, tested via paired-samples t-tests and Cohen's d effect size.",
        "model_used": "Large Language Model (OpenAI GPT-4); Flesch-Kincaid Readability Formulas; Paired-Samples t-Test (t(101) = 10.52, p < 0.001); Cohen's d Effect Size Analysis (d = 1.23).",
        "conclusion": "ChatGPT enhanced readability in 56 of the 102 policies, but unexpectedly worsened overall mean readability scores across the entire corpus (M_original = 42.5 vs M_ChatGPT = 35.3, p < 0.001, d = 1.23). LLM interpretations often introduced secondary legal abstractions and complex syntactic structures, proving that naive generative AI summarization cannot be assumed to automatically democratize legal text comprehension.",
        "further_areas_research": "Evaluating targeted few-shot prompts explicitly constraining syntactic complexity and reading grade level; measuring human comprehension and decision-making accuracy through user studies with lay consumers; benchmarking multi-modal visual privacy summary generation."
    },
    {
        "doc_name": "ssrn-4887848.pdf",
        "title": "Towards Perceived Security, Perceived Privacy, and the Universal Design of E-Payment Applications",
        "year": "2024",
        "aim": "To investigate the tripartite relationship between perceived security, perceived privacy, and user interface usability in mobile electronic payment applications to establish universal design guidelines.",
        "objectives": "1. Develop an interactive high-fidelity e-payment mobile prototype incorporating cutting-edge authentication, QR-code payments, and privacy disclosures.\n2. Conduct an empirical in-lab usability evaluation with diverse participants.\n3. Formulate universal design recommendations bridging usability and security perceptions.",
        "research_questions": "RQ: How do user interface design, visual layout, and usability features in mobile e-payment applications shape user perceptions of underlying security and privacy robustness?",
        "methodology": "Mixed-methods laboratory usability study. Created a high-fidelity interactive prototype (Figma) and recruited N=12 diverse adult participants (screened from 16 applicants) for hands-on interactive task completion, followed by comprehensive semi-structured interviews evaluating security, privacy, and usability.",
        "model_used": "High-Fidelity Mobile Prototyping; Universal Design Principles; Semi-Structured Qualitative Interviewing; Usable Privacy and Security Interaction Model.",
        "conclusion": "Usability strongly biases security perception: users frequently judge the cryptographic and transactional security of an e-payment app directly by the polish, layout, and visual fluency of its GUI. Participants endorsed biometric authentication and QR-code transfers but demanded granular control over app permissions, notification transparency, and simplified identity verification.",
        "further_areas_research": "Conducting quantitative structural equation modeling (SEM) to statistically measure the causal path between UI usability and security trust; evaluating prototypes across wider demographic cross-sections (seniors, low-literacy users); performing field trials with live financial transactions.",
    },
    {
        "doc_name": "ssrn-4991487.pdf",
        "title": "Evaluating Privacy Measures in Healthcare Apps Predominantly Used by Older Adults",
        "year": "2024",
        "aim": "To quantitatively evaluate the privacy protections, regulatory compliance, and data-handling transparency of mobile healthcare applications predominantly designed for and used by older adults.",
        "objectives": "1. Establish a comprehensive Privacy Risk Assessment Framework (PRAF) tailored for geriatric digital health.\n2. Audit 28 mobile healthcare applications targeted at older adults.\n3. Assess explicit compliance with HIPAA and GDPR, data breach disclosure policies, and third-party tracking disclosures.",
        "research_questions": "RQ1: To what extent do mobile healthcare applications designed for older adults comply with essential health privacy regulations (HIPAA, GDPR)?\nRQ2: What data handling, sharing, and breach notification practices do these applications disclose in their privacy policies?",
        "methodology": "Multi-dimensional privacy audit of N=28 healthcare apps targeted at older adults (telehealth, medication reminders, vital sign monitoring). Evaluated across regulatory compliance, data collection, third-party sharing, data retention, breach notification protocols, and usability/readability.",
        "model_used": "Privacy Risk Assessment Framework (PRAF); Comparative Regulatory Benchmarking (HIPAA & GDPR); Content Analysis & Privacy Scoring Index.",
        "conclusion": "Significant privacy and regulatory voids exist in apps serving older adults: only 25% of apps explicitly complied with HIPAA, and only 18% adhered to GDPR. A staggering 79% of apps lacked any documented data breach notification protocol, leaving vulnerable aging users unaware when sensitive medical and personal data is compromised.",
        "further_areas_research": "Dynamic traffic analysis to detect undeclared background data leakage to ad-trackers; co-designing simplified, accessible privacy notices for older adults; regulatory investigations into health app privacy compliance beyond traditional covered entities."
    },
    {
        "doc_name": "ssrn-5673790.pdf",
        "title": "Systematic Literature Review of Vulnerabilities and Defenses in VPNs, Tor, and Web Browsers",
        "year": "2024",
        "aim": "To conduct an exhaustive systematic literature review mapping architectural vulnerabilities, adversarial attack vectors, and defensive countermeasures across three core pillars of web privacy: VPNs, Tor, and web browsers.",
        "objectives": "1. Synthesize research on vulnerabilities in browser runtimes, extension APIs, and network-layer privacy tools.\n2. Map common attack models including WebRTC IP leaks, DNS leaks, fingerprinting, memory forensics, and traffic correlation.\n3. Evaluate proposed defenses and analyze systemic interactions between layered privacy technologies.",
        "research_questions": "RQ1: What architectural vulnerabilities and threat vectors undermine the security and privacy guarantees of web browsers, VPNs, and Tor?\nRQ2: How effectively do proposed defense mechanisms protect user anonymity, and what vulnerabilities emerge when these privacy tools interact?",
        "methodology": "Systematic Literature Review (SLR) filtering an initial corpus of 552 peer-reviewed articles down to N=19 high-impact studies based on rigorous inclusion criteria. Conducted architectural threat modeling and comparative analysis of defense mechanisms across network and application layers.",
        "model_used": "PRISMA Systematic Literature Review Protocol; Multi-Layered Architectural Threat Modeling; Comparative Defense Taxonomy.",
        "conclusion": "Standalone privacy tools provide brittle protection: VPNs frequently suffer from WebRTC and DNS IP leaks, browser extensions introduce massive privilege escalation surfaces, and Tor remains vulnerable to advanced traffic correlation and memory-resident forensics. Combining tools often introduces unexpected conflicts that degrade privacy rather than enhancing it.",
        "further_areas_research": "Designing formal provably-secure architectures for multi-layered privacy tool stacks; empirical auditing of commercial VPN client application vulnerabilities; evaluating post-quantum cryptographic defenses against long-term traffic correlation."
    },
    {
        "doc_name": "way2021-jensen.pdf",
        "title": "Multi-Factor Authentication Application Assessment: Risk Assessment of Expert-Recommended MFA Mobile Applications",
        "year": "2021",
        "aim": "To conduct a technical security and vulnerability assessment of expert-recommended mobile Multi-Factor Authentication (MFA) applications to evaluate whether security tools themselves introduce latent risk vectors.",
        "objectives": "1. Conduct a thematic review of 2020 peer-reviewed MFA research.\n2. Perform automated static security and permission vulnerability auditing of 10 leading expert-recommended MFA apps.\n3. Identify cryptographic weaknesses, over-privileged permissions, and insecure third-party tracking components.",
        "research_questions": "RQ: Do mobile authentication applications recommended by cybersecurity experts meet rigorous security standards, or do they harbor latent vulnerabilities that compromise the user's overall security posture?",
        "methodology": "Multi-tool automated static application security testing (SAST) of N=10 expert-recommended MFA mobile apps (Google Authenticator, Microsoft Authenticator, Authy, Duo, Yubico Authenticator, etc.) combined with a thematic literature review of 2020 MFA research across ACM, Google Scholar, and ScienceDirect.",
        "model_used": "Static Application Security Testing (SAST) using Mobile Security Framework (MobSF) and RiskInDroid; Permission Risk Index; Thematic Literature Analysis.",
        "conclusion": "Even expert-recommended MFA applications suffer from alarming security defects: code-level vulnerabilities, weak cryptographic implementations, over-privileged Android permissions, and embedded third-party advertising/tracking libraries. Users seeking to bolster security by installing MFA tools inadvertently introduce new attack surfaces onto their devices.",
        "further_areas_research": "Dynamic runtime penetration testing and token extraction attacks on MFA mobile storage; developing open-source, zero-dependency, tracker-free reference MFA implementations; evaluating usability-security tradeoffs of hardware security keys versus mobile authenticator apps."
    }
]

output_json = r"C:\Users\oladi\.gemini\antigravity-ide\brain\f32186c3-d5d3-4508-a451-07c97b6872f1\scratch\all_papers_analyzed.json"
with open(output_json, "w", encoding="utf-8") as f:
    json.dump(records, f, indent=2, ensure_ascii=False)

print(f"Successfully compiled verified database of {len(records)} papers!")
